### ISSUE TITLE
Player attacking

### ISSUE THREAD

**Issue by Zlrobbins9** [SIG-Game/VampireRun#12]
Allow the player to use a basic projectile at the closest enemy while not moving (similar to the mobile game archero), meaning

- [x] determine which enemy is the closest to the player
- [x] fire a bullet at the enemy when not moving at a predefined rate (pass in the angle and the speed to the bullet)
- [x] create a bullet prefab that moves at the speed and angle passed into it.
- [x] Player bullets should decrease enemy health when they collide with an enemy

**Comment by adenprince** [comment]
Completed in pull request #37.
