### ISSUE TITLE
Pause menu

### ISSUE THREAD

**Issue by Zlrobbins9** [SIG-Game/VampireRun#19]
Create a pause menu toggled by a button that freezes all features of the game (see [Time.timeScale documentation](https://docs.unity3d.com/ScriptReference/Time-timeScale.html)), and contains buttons that allow you to:
- return to level select
- Resume game
- Quit game

**Comment by adenprince** [comment]
Completed on `premain`. The pause button and pause menu UI are too small on mobile devices, but I think mobile scaling issues can be addressed later. Clicking the level select button gives an error because the LevelSelect scene doesn't exist.
