### ISSUE TITLE
Base enemy prefab ranged attack

### ISSUE THREAD

**Issue by Zlrobbins9** [SIG-Game/VampireRun#20]
Enemy can shoot a projectile at the player, meaning

- [x] Enemy can fire a projectile toward player plus customizable variation (pass in the angle and speed to the projectile)
  - The direction vector of the projectile's velocity can be calculated by taking (player position) - (enemy position).
- [x] Basic projectile is created that moves at the same angle it was fired at (at variable speed)

**Comment by adenprince** [comment]
Completed with pull request #27.
