### ISSUE TITLE
Basic player prefab

### ISSUE THREAD

**Issue by Zlrobbins9** [SIG-Game/VampireRun#21]
Have a basic version of the player prefab, meaning

- [x] Basic health system (have a health variable and functions for reducing and increasing health)
- [x] basic sprite (a red rectangle) for the player
- [x] Have a box collider and a rigidbody for the player
- [x] put the prefab in the sample scene

**Comment by adenprince** [comment]
Health changes completed by https://github.com/SIG-Game/VampireRun/pull/24.

**Comment by adenprince** [comment]
Health changes completed by pull request https://github.com/SIG-Game/VampireRun/pull/24. Other changes for this issue were made on `premain`.
