### ISSUE TITLE
score mechanic

### ISSUE THREAD

**Issue by joshjwilli** [SIG-Game/VampireRun#42]
- Overall High Score (finite score + infinite score)
- Per Level Score (each level and infinite mode has an individual score)
- Per level score is made up of, enemies defeated (bosses net more), forward distance traveled (mainly for infinite mode but also allows some points to be rewarded for unfinshed levels), and when the card system is implemented perhaps score related to those mechanics.
- Placeholder text to display these scores where relevant (in-level, per level, and overall high score probably on main menu)

**Comment by adenprince** [comment]
Completed in pull request #51.
